# Generated by Django 3.1.3 on 2020-11-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='moisture',
            field=models.FloatField(default=10),
        ),
    ]
